import DoughnutChart from "@/components/MarketInsight/DoughnutChart";
import MarketInNumbers from "@/components/MarketInsight/MarketInNumbers";
import SectionHeader from "@/components/SectionHeader";
import Chips from "@/components/ui/Chips";
import { CubeTransparentIcon } from "@heroicons/react/24/outline";
import React from "react";
import { Metadata } from "next";
import SectionLayout from "@/components/ui/SectionLayout";


export const metadata: Metadata = {
  title: "Market Trends",
  description: "Generated by create next app",
};

function page() {
  return (
    <>
      <SectionHeader title="Market Trends" image="https://info.cecr.in/wp-content/uploads/3_7.png"/>
      <SectionLayout className="relative">
        <div className=" rounded-lg bg-white p-5 shadow-md">
          <MarketInNumbers />
        </div>
        <div className="mt-10 flex h-full w-full flex-col-reverse gap-10 sm:flex-row">
          <div>
            <DoughnutChart />
          </div>

          <div className="right space-y-3">
            <h1 className="text-4xl font-bold text-heading">Key Trends</h1>

            <ol className="list-disc text-left font-light leading-relaxed text-subheading *:my-2 sm:w-2/3">
              <li>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta
                facilis delectus ab natus praesentium qui voluptatem quos saepe
                hic nemo nihil, ratione in laborum beatae!
              </li>
              <li>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta
                facilis delectus ab natus praesentium qui voluptatem quos saepe
                hic nemo nihil, ratione in laborum beatae!
              </li>
              <li>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta
                facilis delectus ab natus praesentium qui voluptatem quos saepe
                hic nemo nihil, ratione in laborum beatae!
              </li>
              <li>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta
                facilis delectus ab natus praesentium qui voluptatem quos saepe
                hic nemo nihil, ratione in laborum beatae!
              </li>
            </ol>
          </div>
        </div>
        <div className="mt-20 flex h-full w-full flex-col-reverse gap-10 sm:flex-row-reverse">
          <div>
            <DoughnutChart />
          </div>

          <div className="right space-y-3">
            <h1 className="text-4xl font-bold text-heading">Key Challenges</h1>

            <ol className="list-disc text-left font-light leading-relaxed text-[#555] *:my-2 sm:w-2/3">
              <li>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta
                facilis delectus ab natus praesentium qui voluptatem quos saepe
                hic nemo nihil, ratione in laborum beatae!
              </li>
              <li>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta
                facilis delectus ab natus praesentium qui voluptatem quos saepe
                hic nemo nihil, ratione in laborum beatae!
              </li>
              <li>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta
                facilis delectus ab natus praesentium qui voluptatem quos saepe
                hic nemo nihil, ratione in laborum beatae!
              </li>
              <li>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta
                facilis delectus ab natus praesentium qui voluptatem quos saepe
                hic nemo nihil, ratione in laborum beatae!
              </li>
            </ol>
          </div>
        </div>
      </SectionLayout>
      <SectionLayout className="bg-secondary">
        <div className="space-y-2 text-center ">
          <Chips title="Driving factors" />
          <h2 className="text-2xl capitalize text-primary ">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit
          </h2>
        </div>
        <div className="my-5 flex flex-wrap gap-3 sm:flex-nowrap">
          {factors.map((factor, index) => (
            <div className="flex flex-col items-center gap-3 p-2 " key={index}>
              <CubeTransparentIcon height={100} className="text-accent" />
              <h1 className="text-center text-lg font-semibold text-white">
                {factor.title}
              </h1>
              <p className="text-sm text-[#c2c2c2]">{factor.description}</p>
            </div>
          ))}
        </div>
      </SectionLayout>
    </>
  );
}

export default page;

const factors = [
  {
    title: "Disaster Relief",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta facilis delectus ab natus praesentium qui voluptatem quos saepe hic nemo nihil, ratione in laborum",
    icon: (
      <img
        src="https://placehold.co/20X20"
        className="h-20 rounded-full"
        alt="Logo"
      />
    ),
  },
  {
    title: "Research and Development",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta facilis delectus ab natus praesentium qui voluptatem quos saepe hic nemo nihil, ratione in laborum",
    icon: (
      <img
        src="https://placehold.co/20X20"
        className="h-20 rounded-full text-accent"
        alt="Logo"
      />
    ),
  },
  {
    title: "Remote Sensing",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta facilis delectus ab natus praesentium qui voluptatem quos saepe hic nemo nihil, ratione in laborum",
    icon: (
      <img
        src="https://placehold.co/20X20"
        className="h-20 rounded-full text-accent"
        alt="Logo"
      />
    ),
  },
  {
    title: "Affordable Integrated Chips",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta facilis delectus ab natus praesentium qui voluptatem quos saepe hic nemo nihil, ratione in laborum",
    icon: (
      <img
        src="https://placehold.co/20X20"
        className="h-20 rounded-full text-accent"
        alt="Logo"
      />
    ),
  },
];
