import React from "react";
import type { Metadata } from "next";
import QuickTabs from "./(components)/QuickTabs";
import SectionHeader from "@/components/SectionHeader";
import SectionLayout from "@/components/ui/SectionLayout";
import OfficeLocation from "./(components)/OfficeLocation";
import SectionFaq from "./(components)/SectionFaq";

export const metadata: Metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

function page() {
  return (
    <>
      <SectionHeader title="Contact us" />
      <QuickTabs />
      <SectionLayout className="bg-secondary">
        <div className="flex h-full w-full flex-col-reverse gap-10 sm:flex-row">
          <div className="space-y-3 sm:w-1/2">
            <h1 className="text-4xl font-bold text-primary">Contact us</h1>
            <p className="text-left font-light leading-relaxed text-darksubheading sm:w-2/3">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus
              perspiciatis suscipit repudiandae accusamus, rem numquam
              voluptatibus necessitatibus ullam distinctio? Culpa, reprehenderit
              unde assumenda aut possimus provident omnis architecto.
            </p>
            <div>
              <form
                action="/"
                method="post"
                className="flex flex-col items-center gap-5"
              >
                <input
                  type="text"
                  placeholder="Your name"
                  className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                />
                <input
                  type="email"
                  placeholder="email"
                  className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                />
                <textarea
                  id="message"
                  rows={4}
                  className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                  placeholder="Leave a message..."
                ></textarea>
                <button className="inline-flex w-52 justify-center self-start rounded-full bg-accent  px-4 py-2 text-white drop-shadow">
                  Send
                </button>
              </form>
            </div>
          </div>

          <div className="w-1/2">
            <img
              src="https://images.unsplash.com/photo-1555009306-9e3c5b6a66e3?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
              alt="image"
              className="h-[30rem] rounded-2xl object-cover shadow-md"
            />
          </div>
        </div>
      </SectionLayout>
      <OfficeLocation />
      <SectionFaq />
    </>
  );
}

export default page;
