import SectionHeader from '@/components/SectionHeader'
import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

function page() {

  return (
    <>
        <SectionHeader title="Contact us"  />

       
        <section className="w-full p-5 sm:px-32 sm:py-16 sm:bg-white bg-base">
          
        <h2 className='w-1/2 text-heading font-semibold mx-auto text-center'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo perspiciatis, dolore sapiente aut magnam laboriosam, animi, recusandae nihil provident iusto fugit minus. Eveniet, dolorem! Necessitatibus.</h2>
            <div className="flex flex-col-reverse sm:flex-row mt-20 gap-10 w-full h-full">
                <div className="right space-y-3 sm:w-1/2">
                    <h1 className="text-4xl font-bold text-heading">Contact us</h1>
                    <p className="text-[#555] font-light sm:w-2/3 text-left leading-relaxed">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus perspiciatis suscipit repudiandae accusamus, rem numquam voluptatibus necessitatibus ullam distinctio? Culpa, reprehenderit unde assumenda aut possimus provident omnis architecto? Quo magni dolore unde facere esse dolorum enim? Dolorem, incidunt, cupiditate voluptatem impedit deserunt maxime est sequi voluptates, autem culpa vel alias consequuntur magnam obcaecati natus dolor.
                    </p>
                </div>
                <div className='w-2/4'>
                    <form action="" method="post" className="flex flex-col gap-5">
                    <input type="text" placeholder='Your name' className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"/>
                    <input type="email" placeholder='email' className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"/>
                    <textarea id="message" rows={4} className="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Leave a message..."></textarea>
                    <button className="bg-[#555] text-white p-3 rounded-md">Send</button>
                    </form>
                </div>
            </div>

        </section>

        <section className='w-full p-5 sm:px-32 sm:py-16 sm:bg-white bg-base'>
         

          <div className="flex flex-col sm:flex-row gap-10 mt-10">
            <div className="w-1/2 space-y-3">
              <h2 className="text-2xl font-semibold text-heading">Our Office</h2>
              <p className="text-[#555] font-light text-left leading-relaxed">
                1234 Street Name, City Name, United States
              </p>
              <p className="text-[#555] font-light text-left leading-relaxed">
                +123 456 7890
              </p>
              <p className="text-[#555] font-light text-left leading-relaxed"></p>
              </div>
              </div>
        </section>

    </>
  )
}

export default page