import React from "react";
import SectionHeader from "@/components/SectionHeader";
import AboutUs from "./(componets)/AboutUs";
import ClientCaurosal from "./(componets)/ClientCaurosal";
import Team from "./(componets)/Team";
import aboutbg from "@/assets/images/aboutbg.webp";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "About Us",
  description: "Generated by create next app",
};
function page() {
  return (
    <>
      <SectionHeader title="About Vista" image={aboutbg} />
      <AboutUs/>
      <ClientCaurosal/>
      <Team/>
   
    </>
  );
}

export default page;

