import DoughnutChart from "@/components/MarketInsight/DoughnutChart";
import MarketInNumbers from "@/components/MarketInsight/MarketInNumbers";
import SectionHeader from "@/components/SectionHeader";
import Chips from "@/components/ui/Chips";
import { CubeTransparentIcon } from "@heroicons/react/24/outline";
import React from "react";
import { Metadata } from "next";
import SectionLayout from "@/components/ui/SectionLayout";
import cnbg from "@/assets/images/cnbg.png";
import SectionContact from "@/components/SectionContact";


export const metadata: Metadata = {
  title: "Market Trends",
  description: "Generated by create next app",
};

const dummy = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta facilis delectus ab natus praesentium qui voluptatem quos saep'
                
function page() {
  return (
    <>
      <SectionHeader title="Market Trends" image={cnbg}/>
      <SectionLayout className="bg-primary2">
        <div className=" rounded-lg bg-white p-5 shadow-md">
          <MarketInNumbers />
        </div>
        <div className="mt-10 flex h-full w-full items-center flex-col-reverse gap-10 sm:flex-row">
          <div>
            <DoughnutChart />
          </div>

          <div className="right space-y-5">
            <h1 className="text-4xl font-bold text-heading">Key Trends</h1>

            <ol className="list-disc text-left font-light leading-relaxed text-subheading *:my-2 sm:w-2/3">
              {Array(4).fill(dummy).map((item, index) => (
                <li key={index}>{item}</li>
              ))}
              
            </ol>
          </div>
        </div>
        <div className="mt-20 flex h-full w-full items-center flex-col-reverse gap-10 sm:flex-row-reverse">
          <div>
            <DoughnutChart />
          </div>

          <div className="right space-y-5">
            <h1 className="text-4xl font-bold text-heading">Key Challenges</h1>

            <ol className="list-disc text-left font-light leading-relaxed text-[#555] *:my-2 sm:w-2/3">
            {Array(4).fill(dummy).map((item, index) => (
                <li key={index}>{item}</li>
              ))}
            </ol>
          </div>
        </div>
      </SectionLayout>
      <SectionContact/>
      <SectionLayout className="bg-white">
        <div className="space-y-2 text-center ">
          <Chips title="Driving factors" />
          <h2 className="text-2xl capitalize text-heading ">
            Lorem ipsum dolor sit amet consectetur adipisicing elit
          </h2>
        </div>
        <div className="my-12 grid lg:grid-cols-4 gap-5">
          {factors.map((factor, index) => (
            <div className="flex flex-col items-center gap-3 p-5 cursor-pointer hover:bg-accent/80 rounded-md group " key={index}>
              <CubeTransparentIcon  className="text-accent group-hover:text-white size-20 " />
              <h1 className="text-center text-lg font-semibold text-heading group-hover:text-white">
                {factor.title}
              </h1>
              <p className="text-sm text-subheading text-center group-hover:text-white">{factor.description}</p>
            </div>
          ))}
        </div>
      </SectionLayout>
      
    </>
  );
}

export default page;

const factors = [
  {
    title: "Disaster Relief",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta facilis delectus ab natus praesentium qui voluptatem quos saepe hic nemo nihil, ratione in laborum",
    icon: (
      <img
        src="https://placehold.co/20X20"
        className="h-20 rounded-full"
        alt="Logo"
      />
    ),
  },
  {
    title: "Research and Development",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta facilis delectus ab natus praesentium qui voluptatem quos saepe hic nemo nihil, ratione in laborum",
    icon: (
      <img
        src="https://placehold.co/20X20"
        className="h-20 rounded-full text-accent"
        alt="Logo"
      />
    ),
  },
  {
    title: "Remote Sensing",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta facilis delectus ab natus praesentium qui voluptatem quos saepe hic nemo nihil, ratione in laborum",
    icon: (
      <img
        src="https://placehold.co/20X20"
        className="h-20 rounded-full text-accent"
        alt="Logo"
      />
    ),
  },
  {
    title: "Affordable Integrated Chips",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta facilis delectus ab natus praesentium qui voluptatem quos saepe hic nemo nihil, ratione in laborum",
    icon: (
      <img
        src="https://placehold.co/20X20"
        className="h-20 rounded-full text-accent"
        alt="Logo"
      />
    ),
  },
];
