import DoughnutChart from "@/components/MarketInsight/DoughnutChart";
import MarketInNumbers from "@/components/MarketInsight/MarketInNumbers";
import SectionHeader from "@/components/SectionHeader";
import React from "react";
import { Metadata } from "next";
import SectionLayout from "@/components/ui/SectionLayout";
import cnbg from "@/assets/images/cnbg.png";
import SectionContact from "@/components/SectionContact";
import SectionAbout from "@/components/SectionAbout";
import { GiThunderStruck } from "react-icons/gi";
import { HiMiniDocumentMagnifyingGlass } from "react-icons/hi2";
import { GoRocket } from "react-icons/go";
import { FaHandshake } from "react-icons/fa";

export const metadata: Metadata = {
  title: "Market Trends",
  description: "Generated by create next app",
};



const factorsArray = {
  trends: [
    {
      id: 1,
      content:
        "Miniaturization and portability are two key trends driving the unmanned aerial vehicle (UAV) industry.",
    },
    {
      id: 2,
      content:
        "UAVs are becoming more compact, lightweight, and portable, making them more accessible to a wider range of users.",
    },
  ],
  challenges: [
    {
      id: 1,
      content:
        "Ethical considerations about the use of UAVs and strict government regulations regarding the use of the devices may restrain the market growth.",
    },
    {
      id: 2,
      content:
        "In addition, unmanned aerial vehicles generate kinetic energy after crashes. This poses a threat to these technologies and might hamper market growth.",
    },
  ],
};

function page() {
  return (
    <>
      <SectionHeader title="Market Trends" image={cnbg} />

      <SectionLayout>
        <div className="rounded-lg bg-white p-5 shadow-md">
          <MarketInNumbers />
        </div>
      </SectionLayout>

      <SectionAbout
        chips="overview"
        imageStyle="h-[60vh]"
        cta="contact"
        className="lg:h-[60vh]"
        heading="Market Overview: An analysis on Drone Market"
        para="In the last few years, the drone market has grown a lot because of better technology, cheaper prices, and more ways to use them. Drones are now used for lots of things like taking pictures and videos from the sky, checking on farms, looking at buildings, and even delivering packages. The following Data gives us an overview on Drone Market."
      />

      <SectionLayout className="bg-white">
        <div className="mt-10 grid lg:grid-cols-2">
          <div>
            <DoughnutChart width={500} height={500} options={{
              chart : {
                id:'grip',
              },
              colors : ['#543310','#73512C','#B08F70','#8A704B','#AE926C','#D0BA98'],
              labels: ['Saudi Arab', 'UAE', 'Qatar', 'Kuwait', 'Oman', 'Orange'],
              

            }} series={[{
              name : 'grip',
              data : [12, 19, 3, 5, 2, 3]
            }]} type="area" />
          </div>

          <div className="right space-y-5">
            <h1 className="text-4xl font-bold text-heading">Key Challenges</h1>

            <ol className="list-disc text-left font-light  text-subheading *:my-2 ">
              {factorsArray.challenges.map(item => (<li key={item.id}>{item.content}</li>))}
            </ol>
          </div>
        </div>
      </SectionLayout>

      <SectionContact />
      <SectionLayout className="bg-white">
        <h2 className="text-2xl font-medium capitalize text-primary lg:text-4xl ">
          Driving Factors
        </h2>
        <div className="my-12 grid gap-5 lg:grid-cols-2">
          {factors.map(({ description, icon: Icon, title }, index) => (
            <div key={index}>
              <div className="flex items-start gap-5">
                <span>
                  <Icon className="size-8 " />
                </span>
                <div>
                  <h3 className="text-lg font-bold leading-none text-heading">
                    {title}
                  </h3>
                  <p className="mt-2 text-sm text-subheading ">{description}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </SectionLayout>
    </>
  );
}

export default page;

const factors = [
  {
    title: "Disaster Relief",
    description:
      "The use of drones to deliver detailed information for disaster relief and the use of unmanned aerial vehicle to investigate natural disasters are expected to drive the market forward",
    icon: GiThunderStruck,
  },
  {
    title: "Research and Development",
    description:
      "Furthermore, the increasing use of unmanned aerial vehicles for scientific exploration and defense research, in addition to government initiatives to support unmanned aerial vehicle research and development, are creating lucrative opportunities for market expansion.",
    icon: HiMiniDocumentMagnifyingGlass,
  },
  {
    title: "Remote Sensing",
    description:
      "Sensor and camera development and design are critical for UAV/drone-based remote sensing technology development. Sensor and technology development lead to lower prices for drone components such as ICs (controllers, GPS)",
    icon: GoRocket,
  },
  {
    title: "Affordable Integrated Chips",
    description:
      " Drones are becoming more affordable as the costs of various ICs (controllers, GPS), IoT sensors,MEMSsensors, and batteries fall while their performance improves, such as GPS accuracy.",
    icon: FaHandshake,
  },
];
