import React from "react";
import type { Metadata } from "next";
import QuickTabs from "./(components)/QuickTabs";
import SectionHeader from "@/components/SectionHeader";
import SectionLayout from "@/components/ui/SectionLayout";
import SectionFaq from "./(components)/SectionFaq";
import Chips from "@/components/ui/Chips";

import contactbg from "@/assets/images/contact-bg.jpg";
import Form from "./(components)/Form";
export const metadata: Metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};

function page() {
  return (
    <>
      <SectionHeader title="Lets Talk" image={contactbg} />
      <SectionLayout className="bg-neutral-100 flex w-full lg:items-start   lg:flex-row flex-col">
        <div className="">
      <div className="space-y-3 ">
          <Chips title="Contact us" />
          <h2 className="text-4xl font-bold text-heading ">Contact With Us</h2>
          <p className="text-subheading sm:w-1/2">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Magnam, qui.
          </p>
        </div>
      <QuickTabs />

        </div>
        <div className="flex-1">
          <div className="space-y-3">
            <Form/>
          </div>

       
        </div>
      </SectionLayout>

      <SectionFaq />
    </>
  );
}

export default page;
