import React from "react";
import SectionProjects from "@/components/SectionProjects";
import SectionHeader from "@/components/SectionHeader";
import ServiceCards from "@/components/Services/ServiceCards";
import DroneApplication from "@/components/Services/DroneApplication";
import DroneTech from "@/components/Services/DroneTech";
import { Metadata } from "next";
import FAQ from "@/components/FAQs/FAQ";
import SectionLayout from "@/components/ui/SectionLayout";

export const metadata: Metadata = {
  title: "Services",
  description: "Generated by create next app",
};
function page() {
  return (
    <>
      <SectionHeader title="Discover our services" />
      <ServiceCards />
      <DroneApplication />
      <DroneTech />
      <SectionProjects />
      <SectionLayout>
      <FAQ/>

      </SectionLayout>
    </>
  );
}

export default page;
