import React from "react";
import SectionProjects from "@/components/SectionProjects";
import SectionHeader from "@/components/SectionHeader";
import ServiceCards from "@/components/Services/ServiceCards";
import DroneApplication from "@/components/Services/DroneApplication";
import DroneTech from "@/components/Services/DroneTech";
import { Metadata } from "next";
import SectionContact from "@/components/SectionContact";


export const metadata: Metadata = {
  title: "Services",
  description: "Generated by create next app",
};
function page() {
  return (
    <>
      <SectionHeader title="DRONE SERVICES - AERIAL AND COMMERCIAL DRONE SERVICES" image="https://feds.ae/wp-content/uploads/2022/07/Drone-Solution-End-to-end.jpg"/>
      <ServiceCards />
      <DroneApplication />
      <DroneTech />
      <SectionProjects />
  
      
    </>
  );
}

export default page;
