import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ui/ScrollToTop";
import NextTopLoader from 'nextjs-toploader'
const font = Inter({
  weight: ["200","300", "400", "500", "600", "700","800","900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vista Drone Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className}`}>
        <NextTopLoader showSpinner={false} height={4} />
        <Navbar />
        <main>{children}</main>
        <Footer />
        <ScrollToTop/>
      </body>
    </html>
  );
}
