import React from "react";
import SectionContact from "@/components/SectionContact";
import SectionHeader from "@/components/SectionHeader";
import AboutUs from "./(componets)/AboutUs";
import ClientCaurosal from "./(componets)/ClientCaurosal";
import Team from "./(componets)/Team";

import { Metadata } from "next";
export const metadata: Metadata = {
  title: "About Us",
  description: "Generated by create next app",
};
function page() {
  return (
    <>
      <SectionHeader title="About Vista" image="https://i0.wp.com/www.globaltrademag.com/wp-content/uploads/2022/12/Why-Construction-Companies-are-Opting-for-Drone-Services.png?fit=1600%2C1064&ssl=1" />
      <AboutUs/>
      <ClientCaurosal/>
      <Team/>
      <SectionContact/>
    </>
  );
}

export default page;

