import React from "react";
import SectionContact from "@/components/SectionContact";
import SectionHeader from "@/components/SectionHeader";
import AboutUs from "./(componets)/AboutUs";
import ClientCaurosal from "./(componets)/ClientCaurosal";
import Team from "./(componets)/Team";

import { Metadata } from "next";
export const metadata: Metadata = {
  title: "About Us",
  description: "Generated by create next app",
};
function page() {
  return (
    <>
      <SectionHeader title="About us"/>
      <AboutUs/>
      <ClientCaurosal/>
      <Team/>
      <SectionContact/>
    </>
  );
}

export default page;

