import React from "react";
import SectionProjects from "@/components/SectionProjects";
import SectionHeader from "@/components/SectionHeader";
import ServiceCards from "@/components/Services/ServiceCards";
import DroneApplication from "@/components/Services/DroneApplication";
import DroneTech from "@/components/Services/DroneTech";
import { Metadata } from "next";
import bg from "@/assets/images/Drone-Solution.jpg";

export const metadata: Metadata = {
  title: "Services",
  description: "Generated by create next app",
};
function page() {
  return (
    <>
      <SectionHeader title="DRONE SERVICES - AERIAL AND COMMERCIAL DRONE SERVICES" image={bg}/>
      <ServiceCards />
      <DroneApplication />
      <DroneTech />
      <SectionProjects />
  
      
    </>
  );
}

export default page;
